[build]
  command = "yarn workspace @celo-composer-minipay-template/react-app build"
  publish = "packages/react-app/build"
[build]
  command = "yarn workspace @celo-composer-minipay-template/react-app build"
  publish = "packages/react-app/build"

